### ISSUE TITLE
Set a maximum number of choices in multi_select

### ISSUE THREAD

**Issue by niiccolas** [piotrmurach/tty-prompt#100]
Hello Piotr,
Many thanks for TTY, it's been most helpful. I'm currently using `multi_select` in a project where out of five possible selections, the length of the return value should be no more than three.
Could the method take an option to limit the number of selections? 

Something like
```
choices = %w(vodka beer wine whisky bourbon)
prompt.multi_select("Select drinks (max. 3)?", choices, max_choices: 3)
```
 
where as soon as the selections array length hits the limit, remaining selections become unresponsive to space bar, possibly also greyed out for U.I.:
```
# Select drinks (max. 3)? beer, wine, bourbon
#   ⬡ 1) vodka # unresponsive & greyed out
#   ⬢ 2) beer
#   ⬢ 3) wine
#   ⬡ 4) whisky # unresponsive & greyed out
# ‣ ⬢ 5) bourbon
```

**Comment by piotrmurach** [comment]
Hi Nicolas,

Thank you for using this gem!

This sounds like a plausible request. I can see the utility in having a limit put on the number of options that can be selected. I would probably choose `:limit` as the option name. Would you mind submitting a PR?

**Comment by niiccolas** [comment]
Hi Piotr,
`:limit` sounds good.
I'll look into submitting a PR.

**Comment by Cyraus** [comment]
I want to set minimum number of choices in multi select (or 'required' in select & multi select).

**Comment by piotrmurach** [comment]
@Cyraus I appreciate your support for new features. Instead of piggybacking on already closed and done issue, please open a new one with a description of how things should work similarly to this issue. For extra kudos, how about submitting PR implementing your ideas as well?
