### ISSUE TITLE
Select do not work when called in script

### ISSUE THREAD

**Issue by Vento-Nuenenen** [piotrmurach/tty-prompt#102]
Hello @all 

I built an bash- / ruby-script which helps to set up some Mac OS computers.
The bash part of the system pulls and installs the environment required by the script.
The ruby part installs the tools & configures the device.

Now I use TTY-Prompt to select the environment which shold get deployed on the maschine.
But when the ruby-script is called, tty-prompt dont work. It's only showing the menu, but I can't select the points.

For reproduction watch https://gitlab.com/fadendaten/mac-setup-script

* OS version: Mac OS 10.14.3 / Ubuntu Server 16.04.5
* Ruby version: 2.6.1 / 2.5.1 / 2.3.1
* TTY version: 0.17.1 / 0.17.2 / 0.18.1

**Comment by piotrmurach** [comment]
Hi Vento,

Thanks for using this gem!

I can assure you that I've put a lot of effort into making sure this works in a lot of platforms including 10-year-old windows power shell. The reason why the prompt won't work is when your terminal doesn't support ANSI codes. In other words, there is something fundamental missing from your system that doesn't support interactive shell. If you're, for example, using your script on non-interactive, non-login shell then all bets may be off.
