### ISSUE TITLE
readme doesn't include require

### ISSUE THREAD

**Issue by varioustoxins** [piotrmurach/tty-prompt#105]
the readme doesn't mention anywhere that you need to require 'tty-prompt'...

**Comment by piotrmurach** [comment]
@varioustoxins Thanks for using this gem.

Unfortunately, none of my projects mention this. I assume that this falls under the basics of knowing how to use external libraries in Ruby. This is probably my blind spot after using Ruby for so long 😓  Would you mind submitting PR to remedy this?
