### ISSUE TITLE
page_help isn't available on select or multi_select

### ISSUE THREAD

**Issue by benjamin-hull** [piotrmurach/tty-prompt#108]
The Readme shows that `page_help` can be set on select menus:

```
prompt.select("Choose your letter?") do |menu|
  menu.page_help '(Wiggle thy finger up or down to see more)'
end
```

It looks like the method and config is available on EnumList, but not List, which would allow it to be used for select and multi_select.

If there's not a reason for this, I'm happy to fix and submit a PR. I have only just started using the lib, though, so by all means let me know if I'm missing something!

* OS version: MacOS 10.14.5
* Ruby version: 2.5.3
* TTY version: 0.19.0

**Comment by piotrmurach** [comment]
Hi Ben,

The `select` and `multi_select` used to have `:page_help` option but I got rid of it in the latest release by collapsing all help info into a single help configuration. So the `:help` and `help` method should work fine. Do you have time to submit PR to fix the docs?

**Comment by benjamin-hull** [comment]
Hey, no problem. Yep, will submit a PR for the docs.

I'm really enjoying working with ttytoolkit, by the way. Excellent work!
