### ISSUE TITLE
Choice#from doesn't differentiate between nil and false

### ISSUE THREAD

**Issue by slowbro** [piotrmurach/tty-prompt#109]
### Describe the problem
When using List#choice (which calls Choice#from) with a `false` value, the value defaults to the name.

### Steps to reproduce the problem
```
require 'tty-prompt'

@prompt = TTY::Prompt.new

ch = @prompt.select( "Testing" ) do |menu|
        menu.choice "A test item", false
end

puts ch.inspect
```

### Actual behaviour
```
$ ruby issue.rb
Testing A test item
"A test item"
```

See [https://github.com/piotrmurach/tty-prompt/blob/master/lib/tty/prompt/choice.rb#L38](choice.rb L38) - using `||` on `value` is defaulting it to the name because `value` is false.

### Expected behaviour
I would expect `value` to be set to false, and `nil` to be what defaults to the name. A proposed fix that works for me:

```
diff --git a/lib/tty/prompt/choice.rb b/lib/tty/prompt/choice.rb
index 91cf97b..14c99b4 100644
--- a/lib/tty/prompt/choice.rb
+++ b/lib/tty/prompt/choice.rb
@@ -36,7 +36,7 @@ module TTY
           if name.is_a?(Hash)
             convert_hash(name)
           else
-            new(name.to_s, value || name.to_s, options || {})
+            new(name.to_s, (value.nil? ? name.to_s : value), options || {})
           end
         when Hash
           convert_hash(val)
```

Using same reproduction code with the above patch applied:

```
$ ruby ~/code/tty-prompt/issue.rb 
Testing A test item
false
```

### Describe your environment

* OS version: FreeBSD 11.2
* Ruby version: 2.6.3
* TTY version: 0.19.0

**Comment by piotrmurach** [comment]
Great spot! The solution sounds good to me. Do you have time to submit PR with a test case?

**Comment by slowbro** [comment]
Will do!
