### ISSUE TITLE
Questions with line breaks are repeated on every keystroke

### ISSUE THREAD

**Issue by dgmora** [piotrmurach/tty-prompt#111]
### Describe the problem
I have searched around but did not find the issue, or how to work around it. If I make a question with a line break, the output is not what i would expect

### Steps to reproduce the problem
```bash
2.6.3 :002 > require 'tty/prompt'
 => true
2.6.3 :003 > TTY::Prompt.new.ask("This value is not set.\nSet a value:")
# Start typing
```

### Actual behaviour
When the user is allowed to start typing on every keystroke the first line is repeated.

Before typing anything:
```bash
2.6.3 :004 > TTY::Prompt.new.ask("This value is not set.\nSet a value:")
This value is not set.
Set a value:
```

One keystroke:
```bash
2.6.3 :004 > TTY::Prompt.new.ask("This value is not set.\nSet a value:")
This value is not set.
This value is not set.
Set a value: a
```
Two
```bash
2.6.3 :004 > TTY::Prompt.new.ask("This value is not set.\nSet a value:")
This value is not set.
This value is not set.
This value is not set.
Set a value: aa
```

### Expected behaviour
What did you expect to happen?
The user can type as much as he wants, and the only thing changing is the value after `Set a value: `
```bash
2.6.3 :004 > TTY::Prompt.new.ask("This value is not set.\nSet a value:")
This value is not set.
Set a value: 123456
```
### Describe your environment

* OS version: MacOS Mojave 10.14.2
* Ruby version: 2.6.3
* TTY version: 0.19.0

### Also

Thank you so much for this gem, it's amazing

**Comment by slowbro** [comment]
This is actually a bug in tty-reader `read_line`

```
require 'tty-prompt'

p = TTY::Prompt.new
p.read_line("one?\ntwo?")
```

```
[kschiesser@rubydev ~/code/tty-prompt]$ ruby issue-111.rb                                                                                                                                                                                 
one?
one?
one?
one?
one?
one?
one?
one?
two?aaaaaaa
```
