### ISSUE TITLE
Wrong encoding for cyrillic symbols on Windows

### ISSUE THREAD

**Issue by long76** [piotrmurach/tty-prompt#115]
### Describe the problem
tty don't read cyrillic symbols
P.S. i start program in standard cmd

### Steps to reproduce the problem
```ruby
require 'tty-prompt'

prompt = TTY::Prompt.new

name = prompt.ask('Введите имя?')

puts "Ваше имя: #{name}"
```

### Actual behaviour
i write word `Тест` and press `Enter`
what i see
![Wrong word](https://i.ibb.co/nD1JfFG/2019-10-12-204408.png)

### Expected behaviour
i expect see word `Тест` instead of `??aa`

### Describe your environment

* OS version: Windows 7 SP1 x64 
* Ruby version: 2.6.5
* TTY version: 0.19.0

**Comment by piotrmurach** [comment]
Hi,

Thanks for using this gem!

I can confirm the gem works on MacOS and Debian. 

![tty-prompt-cyrillic-works-unix](https://user-images.githubusercontent.com/444312/66720600-8da39300-ee07-11e9-95c2-5d2c75814a00.png)

Would you mind checking if `gets` for gathering input works in your `irb` session?

Let's see if your console supports Cyrillic symbols first.

**Comment by long76** [comment]
@piotrmurach hi i checked `gets`

![2019-10-14_080144](https://user-images.githubusercontent.com/18124433/66730254-231b4300-ee59-11e9-9803-9d1c9105986e.png)

**Comment by piotrmurach** [comment]
So `gets` gives you similar behaviour. The `tty-prompt` is built on top of `gets`.  As you demonstrated yourself the string is `utf-8` encoded. You're forcing it to be `ibm866` encoded which I'm not going to do because that's not a default Ruby encoding.

**Comment by long76** [comment]
@piotrmurach i try fix it with
```ruby
$stdin.set_encoding('ibm866')
```
but it works only for `gets`
code
```ruby
require 'tty-prompt'

$stdin.set_encoding('ibm866')
@prompt = TTY::Prompt.new
puts gets
puts @prompt.ask "Введите имя:"
```
![2019-10-15_211831](https://user-images.githubusercontent.com/18124433/66858196-70023500-ef91-11e9-999f-c52271c3297a.png)

**Comment by piotrmurach** [comment]
Hi,

Have you managed to get this working on Windows?

Unfortunately, on windows I'm using native C API. This means there is little control from Ruby over the encoding of input stream.

You could try the following:

```ruby
require 'tty-prompt'
@prompt = TTY::Prompt.new input: $stdin.set_encoding('ibm866')
@prompt.ask "Введите имя:"
```

**Comment by long76** [comment]
> Hi,
> 
> Have you managed to get this working on Windows?
> 
> Unfortunately, on windows I'm using native C API. This means there is little control from Ruby over the encoding of input stream.
> 
> You could try the following:
> 
> ```ruby
> require 'tty-prompt'
> @prompt = TTY::Prompt.new input: $stdin.set_encoding('ibm866')
> @prompt.ask "Введите имя:"
> ```

Negative, i try code on 0.20.0
![2019-11-25_211412](https://user-images.githubusercontent.com/18124433/69566631-97084980-0fc8-11ea-9961-5d45e55f966b.png)

**Comment by piotrmurach** [comment]
What is exactly the Windows version you're using and the shell? I wonder if I should provide some other feature detection.

**Comment by long76** [comment]
> What is exactly the Windows version you're using and the shell? I wonder if I should provide some other feature detection.

sorry, i forgot reply. it's was Windows 7 SP1 x64

**Comment by piotrmurach** [comment]
I have installed VM for Windows XP, and the encoding doesn't even work for me in the `irb` session without any involvement from `tty-prompt`. Windows 7 is more than a decade old and no longer supported so unless you have time to help and fix this issue, I'm afraid I won't be investigating this any further. I don't have time to put into resolving this issue - sorry! Here's the relevant dependency that handles input [tty-reader](https://github.com/piotrmurach/tty-reader). You're probably in the best position to help debug this issue and suggest possible solution.

You can switch-off specific Windows Input APIs support and use Ruby standard inputs/outputs:

```ruby
prompt = TTY::Propmt.new(env: { "TTY_TEST" => true })
```

**Comment by long76** [comment]
> I have installed VM for Windows XP, and the encoding doesn't even work for me in the `irb` session without any involvement from `tty-prompt`. Windows 7 is more than a decade old and no longer supported so unless you have time to help and fix this issue, I'm afraid I won't be investigating this any further. I don't have time to put into resolving this issue - sorry! Here's the relevant dependency that handles input [tty-reader](https://github.com/piotrmurach/tty-reader). You're probably in the best position to help debug this issue and suggest possible solution.
> 
> You can switch-off specific Windows Input APIs support and use Ruby standard inputs/outputs:
> 
> ```ruby
> prompt = TTY::Propmt.new(env: { "TTY_TEST" => true })
> ```

okay, thanks!
