### ISSUE TITLE
Change color of certain prompts

### ISSUE THREAD

**Issue by jcampbell05** [piotrmurach/tty-prompt#12]
I would like to change the color of certain prompts such as the default value prompt and the "use arrow keys to move up and down"

They end up being black which blends in with black terminals.

**Comment by piotrmurach** [comment]
Sure thing, would you mind listing exactly which prompts and what you need changing? For example, for `select` and `multi_select` prompts you can change help text by passing `:help` [see](https://github.com/piotrmurach/tty-prompt#27-select) I would be interested to see screenshot of the prompt you are making? Also, if you could provide example(s) of how you envisage the code working I'm happy to change things.

**Comment by jcampbell05** [comment]
<img width="320" alt="screen shot 2016-03-25 at 14 16 10" src="https://cloud.githubusercontent.com/assets/1484989/14045691/28871900-f294-11e5-88ad-f30b82497ff8.png">
<img width="350" alt="screen shot 2016-03-25 at 14 16 15" src="https://cloud.githubusercontent.com/assets/1484989/14045692/288aa872-f294-11e5-949b-f1514a66d98a.png">

See above that the default is printed as black so it isn't shown unless highlighted in dark terminals. (Same for the prompt for multi_select )

<img width="412" alt="screen shot 2016-03-25 at 14 18 12" src="https://cloud.githubusercontent.com/assets/1484989/14045728/6d2acb74-f294-11e5-8cad-9e26486e5ad7.png">
<img width="402" alt="screen shot 2016-03-25 at 14 18 21" src="https://cloud.githubusercontent.com/assets/1484989/14045730/71720030-f294-11e5-8fde-b46cc810df8c.png">


Also if a default value is provided but its empty i.e "" or nil, then a "()" is still printed.

**Comment by piotrmurach** [comment]
Cheers, that really helps! I use black background terminals, i.e. on Debian and the help is visible(it's grayish). I will probably change the default colour to one with more contrast and also allow for setting one for the whole prompt business.  For the moment you should be able to pass in `:help` option with coloured string?

Thanks for spotting the bug, will fix! This is all good stuff, please keep on reporting, PRs are welcome as well.

**Comment by jcampbell05** [comment]
@piotrmurach Sure! Yeah being able to theme will be a big help. Will try to do some PRs to help :)

**Comment by piotrmurach** [comment]
Hi @jcampbell05, just released `v0.5.0` that fixes these issues and allows you to change color settings to your hearts content, please [read](https://github.com/piotrmurach/tty-prompt#2210-active_color). Hope you like it.

**Comment by jcampbell05** [comment]
That is great many thanks !
