### ISSUE TITLE
Ctrl-D from prompt.ask

### ISSUE THREAD

**Issue by purplejacket** [piotrmurach/tty-prompt#121]
### Describe the problem
Is there a way to detect if the user pressed ctrl-D from an invocation of prompt.ask?

### Steps to reproduce the problem
```
prompt.ask('What is your name?')
```
Run the code in *irb*
press ctrl-D
the value returned is `nil`
But I don't know how to detect if the user pressed ctrl-D

### Describe your environment
MacOS Mojave
Ruby 2.6.3
tty-color (0.5.0)
tty-cursor (0.7.0)
tty-prompt (0.20.0)
tty-reader (0.7.0)
tty-screen (0.7.0)

**Comment by piotrmurach** [comment]
Hi Kai,

Thanks for using this gem! ❤️ 

You can listen to key events. There is a [docs section that talks about this](https://github.com/piotrmurach/tty-prompt#212-keyboard-events). In your case:

```ruby
prompt.on(:keyctrl_d) do |event|
  ...
end
```

A list of all [supported events](https://github.com/piotrmurach/tty-reader#28-supported-events)
