### ISSUE TITLE
allow for help_color to be an Pastel::Detached object

### ISSUE THREAD

**Issue by pjvleeuwen** [piotrmurach/tty-prompt#123]
### Describe the problem
This goal of this ticket is to make it possible to give a `Pastel::Detached` instance as `help_color` argument to `TTY::Prompt#new`. This would make sense since Pastel is used anyway and it would allow for more options.

### Steps to reproduce the problem
```
irb(main):001:0> require 'tty-prompt'
=> true
irb(main):002:0> require 'pastel'               
=> false
irb(main):003:0> pastel = Pastel.new
=> #<Pastel @styles=[]>
irb(main):004:0> fancy_color = pastel.cyan.on_white.underline.detach
=> #<Pastel::Detached styles=[:cyan, :on_white, :underline]>
irb(main):005:0> prompt = TTY::Prompt.new(help_color: fancy_color)
=> #<TTY::Prompt: {:input=>#<IO:<STDIN>>, :output=>#<IO:<STDOUT>>, :prefix=>"", :active_color=>:green, :error_color=>:red, :enabled_color=>nil, :help_color=>#<Pastel::Detached styles=[:cyan, :on_white, :underline]>}
irb(main):006:0> prompt.select('Whats ya eatin?', %i[hamburger fries salad])
Traceback (most recent call last):
       16: from /usr/local/bundle/gems/tty-prompt-0.20.0/lib/tty/prompt/list.rb:404:in `render'
       15: from /usr/local/bundle/gems/tty-prompt-0.20.0/lib/tty/prompt/list.rb:455:in `render_question'
       14: from /usr/local/bundle/gems/tty-prompt-0.20.0/lib/tty/prompt/list.rb:491:in `render_header'
       13: from /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `decorate'
       12: from /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `decorate'
       11: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:60:in `decorate'
       10: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:140:in `lookup'
        9: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:140:in `fetch'
        8: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:141:in `block in lookup'
        7: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:153:in `code'
        6: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:153:in `each'
        5: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:158:in `block in code'
        4: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:236:in `validate'
        3: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:195:in `valid?'
        2: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:195:in `all?'
        1: from /usr/local/bundle/gems/pastel-0.7.3/lib/pastel/color.rb:195:in `block in valid?'
NoMethodError (undefined method `to_sym' for #<Pastel::Detached styles=[:cyan, :on_white, :underline]>)
Did you mean?  to_s
```

### Actual behaviour
Only instance of Symbol or responding to `to_sym` is allowed.

### Expected behaviour
I hoped an instance of `Pastel::Detached` would also work.

### Describe your environment
* OS version: `Ubuntu 18.04.3 LTS`
* Ruby version: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]` (in docker, `FROM ruby:2.6.5`)
* TTY version:
```
gem list tty

*** LOCAL GEMS ***

tty-color (0.5.0)
tty-cursor (0.7.0)
tty-prompt (0.20.0)
tty-reader (0.7.0)
tty-screen (0.7.0)```

**Comment by piotrmurach** [comment]
Hi Paul,

Thanks for using this gem! ❤️ 

My preferred way would be to make it respond to common interface like `call` method. In other words, provide a way to specify color as a lambda. Both, lambda and `Pastel::Detached` respond to the same method. This would make it more flexible.

**Comment by pjvleeuwen** [comment]
Thanks for your idea. Should we maybe change the `Pastel#decorate` method instead of `Prompt#decorate` (as is currently in #124 )?

**Comment by piotrmurach** [comment]
The `pastel` gem is used by many gems and I would need a very good reason to change its api and break many other projects. I don't believe the changes in `pastel` are needed. The reason to use proc is so that you should be able to inject any type of coloring library.

**Comment by piotrmurach** [comment]
I feel as though the `:help_color` should accept both a symbol or `proc` object. When proc gets passed in then the user needs to provide their own coloring:

```ruby
help_color: ->(string) { 3rdPartyLibrary.color(string) }
```

And then the `Prompt#decorate` method would check if `colors` are simple strings or proc object and act accordingly. Would you have time to change your PR?

**Comment by piotrmurach** [comment]
Any callable object, not only `Pastel#detached` can be used as the value for `:active_color`, `:error_color` and `:help_color` values.
