### ISSUE TITLE
yes? - Setting the default to literal string `no` breaks capitalization

### ISSUE THREAD

**Issue by sascha-wolf** [piotrmurach/tty-prompt#126]
### Describe the problem
The default representation of `yes?` is confusing when being overwritten to the literal strings `n`, `no` or `No`. It works as expected when setting it to `false`.

#### `test.rb`
```
require "tty-prompt"

TTY::Prompt.new.yes?("I expect 'Yes' to be selected", default: "no")
```

#### CLI
```
$ ruby test.rb
I expect 'Yes' to be selected (Y/n) 
[ENTER]
I expect 'Yes' to be selected no
```

### Actual behaviour
The default suggestion stays `(Y/n)` - implying `yes` - regardless of whether or not the default is actually `no`.

### Expected behaviour
The default suggestion changes to `(y/N)`.

**OR**

Setting the default to `"no"` is disallowed and `false` needs to be used.

### Describe your environment

* OS version: MacOS Mojave 10.14.6
* Ruby version: 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
* TTY version: 0.18.1

**Comment by piotrmurach** [comment]
Hi Sasha,

Thanks for giving this gem a try.

The only values that the `yes?` prompt `:default` option accepts are `true` and `false`. That's usually the only values expected to be returned by the `yes?` prompt. In general, the semantics behind the default option is "If the user enters nothing and presses enter, use this default as a return value". That's how it is used in the `ask` prompt as well. If we followed your example then the prompt should return the `"no"` value string when nothing is entered. How useful would that be for your application to get `no` string back? For me, probably the suggestion to use validation for boolean only default is a preferred approach.

**Comment by sascha-wolf** [comment]
I'm perfectly fine with either approach. I see the reason in ensuring the value is boolean.

I've mostly opened the issue because I stumbled across this while using a script a colleague had previously written and I didn't notice that the implied default (`Y`) was not the actually used default (the string `no`) which resulted in me thinking a task had been done although it hadn't. 🙂
