### ISSUE TITLE
ctrl-c in pry

### ISSUE THREAD

**Issue by kylekyle** [piotrmurach/tty-prompt#14]
`tty-prompt` in causes `pry` to exit on ctrl-c. It makes it really hard to play in `pry` with any app that uses `tty-prompt`.

**Comment by piotrmurach** [comment]
Hi Kyle, fair point, it would be good to play nicely with inside pry, do you have time to look into it and submit PR?

**Comment by kylekyle** [comment]
Here's the culprit:

> https://github.com/piotrmurach/tty-prompt/blob/master/lib/tty/prompt/reader.rb#L163

I can see why catching it is better than showing the user an `Interrupt` exception in a command line utility, but it really makes the REPL unpleasant. Maybe something like this to allow the `Interrupt`?

```ruby 
prompt = TTY::Prompt.new interrupt: true
```

**Comment by piotrmurach** [comment]
Thanks for investigating, I think I would drop the trapping of interrupt signals and let the user of the library handle the situation, regardless of whether it's run in pry or as stand alone script?

**Comment by ondra-m** [comment]
I still have a problem when List is printed. On ctrl+c is https://github.com/piotrmurach/tty-prompt/blob/4d3a09715a63ad86724d556005d473bb1147ee30/lib/tty/prompt/list.rb#L114 calling.

Custom trap is useless in this case.
