### ISSUE TITLE
Feature request - multi select all

### ISSUE THREAD

**Issue by hatlord** [piotrmurach/tty-prompt#140]
Hello,

First of all, thanks for the amazing Gem, i use it all the time. I was wondering if there is an easy way to select all options when using 'multi_select', and if not could i make a feature request for it?. I wrote a file parser where users can point the tool at a directory and choose which files they want to parse. Occasionally they might want to select all files, so it would be nice if they could just press 'a' for example and grab them all rather than clicking on each one. I cant see any obvious function to do that but maybe im missing something.

Thanks,

Rich

**Comment by piotrmurach** [comment]
Thanks for the suggestion Rich and using `tty-prompt`! 

You're right, it isn't currently possible to select all choices at once. And I really like your feature request idea. I cannot make any guarantees as to when it will be added though. If you have time to provide PR that would be really appreciated.

**Comment by piotrmurach** [comment]
Added ability to select all, non-disabled, choices with `Ctrl+a`. When `:max` option is given, I opted to disable selecting all as it doesn't seem desirable in the context. Using only `a` letter wouldn't work as it would clash with the `:filter` option that allows to search with any letters. Plus I believe that `Ctrl+a` seems natural/intuitive already as a lot of tools support this shortcut. Do you think the help should be extended to include this info?

I was also thinking about supporting `Ctrl+i` to invert the selection in case someone selects all by mistake or wants 'almost' all minus one or two options. Any thoughts?

**Comment by hatlord** [comment]
Thanks for pushing the change! Ctrl+a certainly makes a lot of sense as you say. Inverting would also be useful no doubt!

**Comment by piotrmurach** [comment]
Added `Ctrl+R` to reverting selection. I cannot use `Ctrl+I` as Ruby for some reason doesn't distinguish between Tab & Ctrl+I and returns the same byte codes. I kind of like `Ctrl+R` better as it is a much easier combo to press.

I'm still debating whether I should change the help info to include the new shortcuts? It's kind of already pretty long. If so, do you have any suggestions/preferences?
