### ISSUE TITLE
New TTY::Prompt::Test still complains: undefined method 'ioctl'

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-prompt#148]
### Describe the problem

Trying the new `TTY::Prompt::Test` - there are still issues related to `StringIO`.

### Steps to reproduce the problem

Save the file below, and run `rspec test.rb`

```ruby
# test.rb
require 'tty-prompt'
require "tty/prompt/test"

class Subject
  def prompt
    @prompt ||= TTY::Prompt.new
  end

  def run(print: true)
    result = prompt.ask("Name")
    puts "==> #{result}" if print
  end
end

describe Subject do
  let(:prompt) { TTY::Prompt::Test.new }
  before { allow(subject).to receive(:prompt).and_return prompt }

  describe '#run' do
    it "works" do
      prompt.input << "Danny\n"
      prompt.input.rewind
      expect { subject.run }.to output("==> Danny\n").to_stdout
    end
  end
end
```

### Actual behaviour

```
Failure/Error: result = prompt.ask("Name")

     NoMethodError:
       undefined method `ioctl' for #<StringIO:0x000055cd44bcecd0>
     # /.../tty-screen-0.8.1/lib/tty/screen.rb:216:in `ioctl?'
     # /.../tty-screen-0.8.1/lib/tty/screen.rb:199:in `size_from_ioctl'
     # /.../tty-screen-0.8.1/lib/tty/screen.rb:64:in `size'
     # ...trimmed...
```

### Expected behaviour

It should work. And it does work, when adding the usual patch:

```ruby
class StringIO
  # Not sure if wait_readable is needed
  # def wait_readable(*)
  #   true
  # end

  # ioctl is needed
  def ioctl(*)
    80
  end
end
```

**Comment by piotrmurach** [comment]
Thanks! Ah yes, this is related to `tty-screen` optimizations which evaluates code when it is loaded, which makes it 'impossible' to mock standard output calls for few methods. OK, let's forget about making `TTY::Prompt::Test` public for now. I will remove the section from the docs. I still want to release a new version as it's ready and there are many new features and bug fixes.

**Comment by DannyBen** [comment]
Ok - this was "Death in the cradle"... :)
Goodbye `TTY::Prompt::Test`

**Comment by piotrmurach** [comment]
I'm ruthless like that ;-) I will keep `TTY::Prompt::Test` fine if you wish to use it, it's not going anywhere as it is used internally. But probably I need to put more thought into how to approach testing prompt components. I had a few tries but I wasn't satisfied with any of them. The current approach is pragmatic and it works. I will add docs about `:input` and `:output` so people can use them if they wish, these are not going away anywhere and are part of the API.  I must admit your RSpec approach is growing on me. At least in the realm of `tty-prompt`.

**Comment by piotrmurach** [comment]
I may have been too hasty. How would you feel if I 'refined' StringIO for now in the context `TTY::Prompt::Test`? I'd add both the `wait_readable` and `ioctl` extensions? I'd really like to provide an intermediate solution and one that you can use so that I have immediate feedback on how well it performs. One way or another, `tty-prompt` needs to provide some testing help.

**Comment by DannyBen** [comment]
I fully trust your judgment on this - you know the intricacies of the TTY suite better.
If the `TTY::Prompt::Test` solution is fully rounded, and can provide a nice stubbing target, without dirtying up your code, fine. Otherwise, its not worth moving dirt from one side to the other.

We all want clean code - both in the TTY gem itself, in its test suite, and in the tools that use it.

At this stage, I believe I have better (for myself) solutions than both the Test prompt and the testing gem. I will share later in the "main discussion ticket".

**Comment by piotrmurach** [comment]
I'd like the `TTY::Prompt::Test` to not have any edge-cases that user needs to handle. My preference is for it to work out of the box. All the 'extensions' and specifics that trigger `TTY::Prompt` to work in test mode are then well encapsulated. So now your example will work without `StringIO` modifications.
