### ISSUE TITLE
Optional select

### ISSUE THREAD

**Issue by guillaumebriday** [piotrmurach/tty-prompt#156]
### Describe the problem
A brief description of the issue/feature.

### Actual behaviour
We cannot make a select optional.

### Expected behaviour
In a select, I would like to make it optional, for instance:

<img width="407" alt="Screen Shot 2021-01-14 at 14 36 03" src="https://user-images.githubusercontent.com/8252238/104598074-6c6acb80-5676-11eb-89df-808015914910.png">

### Describe your environment

* TTY::Prompt version: Latest

**Comment by piotrmurach** [comment]
Hi Guillaume 👋 

Thanks for using `tty-prompt`.

I'm not fully sure what you mean by optional select? Would you mind explaining how you imagine this to work? Especially useful would be code and description what the user would do in the select prompt and what keys they would press to achieve what you want.

**Comment by guillaumebriday** [comment]
Hey thanks @piotrmurach for the quick answer! 

As you can see in the image, I want to show a select but the answer is optional. In my answer, users may not want to choose a particular framework for Webpack. That would be great to have an option like `optional: true`.

Or maybe I just use a hash with something like `{ none: nil }` as choice? 🤔

**Comment by piotrmurach** [comment]
Let me explain why I'm a bit sceptical about this request. 

Let's assume we add `optional: true`. What happens then when the menu gets rendered? Do we show a menu without any choice marked by an arrow? Continuing with this thought, we assume that nothing is selected initially. What then? Does moving arrow key down selects a first option or the default one, or maybe the last one? Ok, let's say we for some reason decide that's the first, but what if the user doesn't want to select any option now. What do they press to deselect? Let's say somehow they press some unspecified key and succeed. But how do they select 'lack of choice'. Enter and space are already take for selecting a choice.

All in all, what I'm trying to say is that this is a very confusing experience and I wouldn't necessarily know how it should be implemented. More importantly, does it even need to be implemented?

It seems to me that you're trying to use a wrong tool for the job. Similar to radio buttons in web forms, the `select` prompt is meant to guide a user to pick a single choice. In other words, why show a `select` menu at all if the user doesn't need any JS framework? The more prudent approach would be to first ask a question about whether a user needs a JS framework at all. Only then conditionally display selection menu? Alternatively, as you have alluded to, add a final option `none` that will signify no JS framework. Any thoughts?

**Comment by piotrmurach** [comment]
@guillaumebriday Thank you for contributing this issue. I'm not sure that there is a simple way to implement your request that would be intuitive to the users. I have strong doubts about the use case as well. This is a balancing act between providing prompts and features that people need to implement their terminal apps. In this instance, I feel reluctant about including such an option to the `select` prompt. However, if you think my judgment is faulty then please free to reopen and let's discuss.
