### ISSUE TITLE
Allow wrap-around when using arrow keys to change selection

### ISSUE THREAD

**Issue by vinnydiehl** [piotrmurach/tty-prompt#194]
### Steps to reproduce the problem

* Produce a `#select` with multiple options
* Use the up arrow key while the first option is selected, or the down arrow key while the last option is selected

### Actual behaviour

Nothing happens.

### Expected behaviour

It wraps around to the other end.

**Comment by piotrmurach** [comment]
Hi Vinny 👋 

Thank you for using `tty-prompt`.

The [:cycle](https://github.com/piotrmurach/tty-prompt#2621-cycle) option described in the documentation for the `select` prompt does what you need.

Please bear in mind before you open a ticket on any open-source project to do the following first:

1. Read the documentation.
2. Search open and closed issues.
3. Search the Discussions forum.

As you can appreciate being an open source developer takes valuable resource - time. I'd like to spend it on developing open source. Please support me by being considerate with future issue reports. Thank you.

**Comment by vinnydiehl** [comment]
D'oh! 🤦 Look at me, stupid user, read the docs, how embarrassing. Thanks for the great library, and for being so cordial and helpful.
