### ISSUE TITLE
Request: `filepath` and `pathname` file existance validator

### ISSUE THREAD

**Issue by lulalala** [piotrmurach/tty-prompt#196]
### Describe the problem

Currently there are two convert options: `filepath` and `pathname`.

Does it make sense to provide a built-in way to verify the user entered path exists, and if not, request the user to enter again?
We could name this `file_exists` validator.

**Comment by piotrmurach** [comment]
Hi @lulalala,

I'm not convinced this is a worthwhile addition. My aim with any gem is to provide extension points for easy configuration. This means that I'd rather not take the burden of maintaining custom validators. It's relatively straightforward to add this type of validation:

```ruby
prompt.ask("Provide a filename") do |q|
  q.validate ->(value) { File.exist?(value) } 
end
```

Most likely any user will want to configure the message for this as well. For that reason, I'd opt to keep this out of the gem.
