### ISSUE TITLE
huge select list - a way to follow the cursor ?

### ISSUE THREAD

**Issue by kiuKisas** [piotrmurach/tty-prompt#23]
Hi,
So, I have a huge select list to show, taller than my terminal screen. The issue is that I can't see the top of selection, even if the cursor is on it; does an option exist to fix it ? ( maybe something like htop do)

**Comment by piotrmurach** [comment]
Hi, Thanks for using the library. Good spot, I haven't built anything to
handle selection lists taller than the screen height.  So there is no quick
fix option. I'd imagine that adding a paginator that can return a fixed
slice and allow switching between pages a flexible solution. Do you have
time to work on it or submit patches?

**Comment by kiuKisas** [comment]
Sure, I'll try to do that next week, let you know.

**Comment by kke** [comment]
It's possible to do something like this:

```ruby
# assuming options is an array with 'label' and 'value'
def menu_page(options: [], per_page: 23, page: 0)
  answer = TTY::Prompt.choice do |menu|
    if page > 0
      menu.choice "<< Previous page", { options: options, per_page: per_page, page: page - 1 }
    end
    options[page*per_page..(page*per_page)+per_page].each do |opt|
      menu.choice opt['label'], opt['value']
    end
    if page > 0 && options.size > (page+1)*per_page
      menu.choice ">> Next page", { options: options, per_page: per_page, page: page +1 }
    end
  end
  answer.kind_of?(Hash) ? menu_page(answer) : answer
end

answer = menu_page(options)
```

**Comment by piotrmurach** [comment]
@kke That looks neat and exactly what I imagine an internal paginator would do. When using selection menus, take a slice from all items given what user indicated with arrows keys. 

This is definitely on my list as the highest priority for this library.

**Comment by piotrmurach** [comment]
I still need to make this work for `#multi_select` and `#enum_select`.

**Comment by piotrmurach** [comment]
This is fully implemented in master branch, soon will release new version.

**Comment by piotrmurach** [comment]
New version `v0.9.0` released - enjoy!

**Comment by kiuKisas** [comment]
:+1:
