### ISSUE TITLE
Ability to check input inclusion in array

### ISSUE THREAD

**Issue by dimanyc** [piotrmurach/tty-prompt#27]
Hi,

Is it possible to check input inclusion in array instead of a range? Something similar to:

```ruby
available_integers  = [1, 4, 8]

def get_int(available_integers)
  ...
  prompt.keypress('Choose something',
                   in: available_integers) #<= throws 'not a range'
  ...
end
```

Thanks so much for this gem. Saved my life!

**Comment by dimanyc** [comment]
found #13. closing

**Comment by piotrmurach** [comment]
Thanks for you comment, good to hear that the gem is really useful!

Thinking about it, the semantics of `in` option would suggest inclusion in array as well. I will have a look to see if I can make it work for both.
