### ISSUE TITLE
Multiple issues on Windows

### ISSUE THREAD

**Issue by cwenner** [piotrmurach/tty-prompt#31]
Hi,

not sure if I am missing something obvious here but I get multiple issues when trying TTY::Prompt on Windows 7.

## Issues

Specifically, when running the first four examples from the readme - prompt name, like ruby?, secret, destiny - the following happens:

* Upon requiring tty-prompt, a warning message "Cannot find path." is always printed (in Swedish in the screenshot).
* The default name is correctly shown but when proceeding, it skips the following yes/no question. The same happens when other questions precede a yes/no question but not when the question is first. (see screenshot)
* Following questions also overwrite earlier lines (perhaps due to the warning) (see screenshot).
* The masked input, instead of taking masked characters will beep a number of times equal to the string length (plus line terminators). When used as the first
* The select prompt does not permit changing options with arrow keys.

### Code tested

```ruby
require 'rubygems' #not needed but included for completeness
#require 'tty' #later test
require 'tty-prompt'

prompt = TTY::Prompt.new
# Following lines reordered and disabled depending on test.
prompt.ask('What is your name?', default: ENV['USER'])
prompt.yes?('Do you like Ruby?')
prompt.mask("What is your secret?")
prompt.select("Choose your destiny?", %w(Scorpion Kano Jax))
````

### Screenshots

Before entering name
(the first line is a standard Windows warning and translates to "Cannot find path"/"The system cannot find the path specified."?):

![image](https://cloud.githubusercontent.com/assets/10931787/21265323/3f9fb3fc-c3a1-11e6-941b-f50a65441459.png)

After entering name and pressing enter once
(note how second prompt is printed but not queried):
![image](https://cloud.githubusercontent.com/assets/10931787/21265328/46bce7b8-c3a1-11e6-90f1-485bf4f31ca6.png)

## Environment

* Win 7 enterprise, SP1
* ruby 2.3.1p112 2016-04-26 x64-mingw32
* gem 2.6.7
* tty-prompt 0.8.0 installed via gem.
* Later, tty 0.5.0 was added, which pulled in tty-prompt 0.6.0. Issues persisted with a change listed below. Uninstalled all packages and reinstalled only tty-prompt 0.8.0.
* bundle installed but not used here.
* Running from cmd.

## Additional info

* Tried installing tty via gem: no change when not required.
* Requiring tty takes over a minute.
* When requiring tty, the only observed change is when the masked question is presented first. It will be presented twice - once where it takes input as normal without masking, then a second time while beeping.
* The "Cannot find path" message does not appear for other gems.

tty-prompt seems like a great tool for making terminal applications otherwise and not sure if others experience this issue. It might just be Windows 7 or the company environment.

Thanks and merry xmas,
Cenny

**Comment by piotrmurach** [comment]
Hi Cenny,

Thank you for this detailed report, it is really useful!

Firstly, I would recommend for you to read similar [issue](https://github.com/piotrmurach/tty-prompt/issues/25) posted recently for deeper understanding of where I am with Windows support.

When I developed this tool I haven't had Windows in mind at all and never tested it on this system. I currently don't have access to Windows but I will try to download ISO for Windows 10 to play with. I'm happy to merge any patches that actually fix the issues mentioned above and make this tool available for Windows users but this is not my priority.

The plan for the next `v0.9.0` release is to:
* Provide ability to paginate long list selection menus [see issue](https://github.com/piotrmurach/tty-prompt/issues/23)
* Fix reading multibyte character input [see issue](https://github.com/piotrmurach/tty-prompt/issues/29)
* Support switching through menu options using tab
* Allow `in` operator to accept array like data

As you can see this is a bit of a task and until this is done I won't be in position to investigate Windows. Do you have time yourself to help out fixing this stuff?

**Comment by piotrmurach** [comment]
This library relies heavily on ANSI escape sequences for controlling input/output. I wonder if that's a missing factor in Windows 7 terminal. Could you please install ANSICON utility and see if that fixes the issue? [see tutorial](https://web.liferay.com/web/igor.spasic/blog/-/blogs/enable-ansi-colors-in-windows-command-prompt)

**Comment by kke** [comment]
It runs fine when running through the [windows linux subsystem](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide), but that of course may not be a suitable choice for many cases.

**Comment by piotrmurach** [comment]
@kke Would you mind checking master again? I have changed how inputs are read and fixed multibyte characters support. I'm not swearing by it but it seems that this library works fine on regular Windows without linux subsystem according to [these tests on Windows box](https://ci.appveyor.com/project/piotrmurach/tty-prompt)

**Comment by kke** [comment]
Passing tests won't prove much in this case I think. The select/multi select things are still not working, no change from #25 

I don't have the ansicon thing.

**Comment by piotrmurach** [comment]
I think the tests prove only that if you have ansi strings support on windows then this library works no problem. I really would need someone to install the ansicon or similar library in console to prove or disprove this theory. Because only then I could add a section in docs to advise people how to use this library. Would you have time to help me out?

**Comment by kke** [comment]
It looks a bit worse using ansicon it seems.

![image](https://cloud.githubusercontent.com/assets/224971/21296479/7072c16a-c575-11e6-83da-1494ded44777.png)

Cursor keys still do nothing, not in keypress.rb either.

Pressing enter now correctly clears the menu, without ansicon it didn't, but just threw the prompt to the middle of it:

![image](https://cloud.githubusercontent.com/assets/224971/21296492/c0def57e-c575-11e6-934c-634237e995c3.png)

**Comment by kke** [comment]
(it might be that i just don't know how to use ansicon)

**Comment by piotrmurach** [comment]
Since the help text and initial option are not highlighted in color, it makes me think that ANSI escape codes are still not recognised. Hence you cannot move up or down but can press enter. 

Please have a look a [this thread](http://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences) that provides possible fixes for win32 console.

**Comment by piotrmurach** [comment]
The weird characters in your output are unicode characters that are probably not supported, that would be an easy fix.

Last idea to try out. Could you please install the `win32console` gem and require it before `tty-prompt`. Looking at the source, the gem rewrites Ruby printing of escape codes with Windows support.

**Comment by kke** [comment]
Now ansicon made my dos prompt slower than a 300bps modem so I guess it's loaded and doing something, but the colors are still not there. 

win32console requires some native stuff to be compiled, and I don't have any compilers.

**Comment by kke** [comment]
Hmm according to https://github.com/symfony/symfony/issues/17499#issuecomment-243481052 windows 10 should not need ansicon.

**Comment by piotrmurach** [comment]
That's true but you still need to enable flag manually to turn ANSI support on windows 10 on as I think it's off by default.

**Comment by kke** [comment]
I think it's a ruby build issue. You would need to compile a ruby with the flag enabled. Maybe they could make it so in the official release.

**Comment by piotrmurach** [comment]
I think this is a OS flag and you could flip it on through your Ruby code if you directly called out a C function [setConsoleMode](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686033(v=vs.85).aspx) through Ruby bindings.

**Comment by cwenner** [comment]
Wow, thanks you for the quick and thorough responses. Unfortunately I only have a running Windows partition at work atm and I cannot motivate spending too much time on this - I just thought the library would be perfect for a utility.

If you do not support Windows, it's entirely understandable. I did not see any information about it in the Readme so it seems I jumped the gun by assuming it was meant as a cross-platform utility.

**Comment by cwenner** [comment]
Using Ansicon (1.66, precompiled x64 bin), the particular issues change somewhat.

These are the corresponding results of the two screenshots in the initial post:

Before entering name:
![image](https://cloud.githubusercontent.com/assets/10931787/21310045/ffa14af8-c5e0-11e6-94e4-0dc4e66ecfdf.png)

After entering name and pressing enter once:
![image](https://cloud.githubusercontent.com/assets/10931787/21310054/084d8a68-c5e1-11e6-8bdb-525788a5eed9.png)

* Ie it is still skipping the yes/no question (perhaps due to the carriage return?).
* It still overwrites previous lines, though differently.
* The secret no longer beeps and does mask the input. The masking characters are however gobbled (unicode if I had to guess - haven't checked Ansicon settings). From the secret "abc", the display is:
![image](https://cloud.githubusercontent.com/assets/10931787/21310107/468445ba-c5e1-11e6-81a6-ee69f1a6ccda.png)
* The arrow keys still do not work for the select.
* The select prompt looks different from the Readme examples and from @kke's screenshot above (again unicode?)
![image](https://cloud.githubusercontent.com/assets/10931787/21310245/c839bf4a-c5e1-11e6-9637-665d5083f067.png)

* Did not notice this before, but both in cmd and in ansicon, pressing non-arrow keys in `select` raises an exception ('c', 'j' and 'r' tested):


> C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/prompt/mask
_question.rb:44:in `keypress`: undefined method `+` for nil:NilClass (NoMethodEr
ror)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wisper-1.6.1/lib/wisper/broadcasters/send_broadcaster.rb:5:in `public_send`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wisper-1.6.1/lib/wisper/broadcasters/send_broadcaster.rb:5:in `broadcast`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wisper-1.6.1/lib/wisper/registration/object.rb:16:in `broadcast`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wisper-1.6.1/lib/wisper/publisher.rb:65:in `block in broadcast`
        from C:/Ruby23-x64/lib/ruby/2.3.0/set.rb:306:in `each_key`
        from C:/Ruby23-x64/lib/ruby/2.3.0/set.rb:306:in `each`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wisper-1.6.1/lib/wisper/publisher.rb:64:in `broadcast`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/prompt/reader.rb:166:in `emit_key_event`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/prompt/reader.rb:79:in `block (3 levels) in read_keypress`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/prompt/reader/mode.rb:36:in `raw`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/reader/mode.rb:36:in `raw`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/reader.rb:77:in `block (2 levels) in read_keypress`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/reader/mode.rb:24:in `echo`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/reader.rb:76:in `block in read_keypress`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/reader.rb:60:in `buffer`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/reader.rb:75:in `read_keypress`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/list.rb:167:in `render`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt/list.rb:96:in `call`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt.rb:231:in `invoke_select`
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tty-prompt-0.8.0/lib/tty/pro
mpt.rb:167:in `select`
        from tty_test2.rb:10:in `<main>`

**Comment by piotrmurach** [comment]
@cwenner This is super helpful. The only thing I would suggest for the future is to test against the master branch as there may be some tiny improvements. I will soon release a new version as well.

Based on these discussion so far I have a few things to look at on Windows:
* Fix "Cannot find the path" [issue in pastel](https://github.com/piotrmurach/pastel/issues/16)
* Detect Windows and replace Unicode characters with some standard ascii
* Investigate a native Windows way to read console input

Any other thoughts what I can investigate that may help to provide basic Windows support?

**Comment by piotrmurach** [comment]
@cwenner @kke @danielpclark I could do with some help checking Windows. Pretty much all prompts should work as expected apart from `mask`. Things I have done:
* Native Windows support for keypress reading which means that `select`, `multi_select` finally work as expected
* Replacement of unicode chars on Windows with equivalent
* Support basic colors in Windows console

This is all available in master branch, I haven't released a new version yet.

**Comment by kke** [comment]
`select`, `multi_select`, `ask`, `yes?`  all seem to work fine from master in a Win10 virtual machine.

**Comment by kke** [comment]
I think your `windows?` is true for cygwin (or MinTTY which also comes with git for windows). Seems like the windows keyreader does not work under it. (the normal non-windows stuff should work fine)

**Comment by piotrmurach** [comment]
I use windows xp image in my vm, but I think other people having a go at testing may uncover different things. I'm happy to refine the current `windows?` check but I wouldn't want to make this a show stopper. It is obviously a double negative cause when people use cygwin the normal unix mode should be just fine provided this check is fixed. 

I'm going to close this ticket as the said issues have been fixed and any future problems like cygwin will warrant a new ticket.
