### ISSUE TITLE
per_page option issue

### ISSUE THREAD

**Issue by keepcosmos** [piotrmurach/tty-prompt#34]
Very thanks for adding per_page option that is what i exactly want. :)

But only one issue is question title is reproduced each time arrow key is pressed
when elements are less than `per_page` value. <- I am sure only this case happen or not.

**Comment by piotrmurach** [comment]
Thanks for reporting! I haven't tested well the case when there is less options than `per_page` param. 

Screenshot to remind me about the problem: 
![screen shot 2017-01-08 at 12 40 03](https://cloud.githubusercontent.com/assets/444312/21749857/b36cf352-d59f-11e6-9416-53b9f57456e4.png)

**Comment by kke** [comment]
Also there doesn't seem to be a way to set default `per_page`

**Comment by kke** [comment]
If you set per_page to 15 and you have 14 items, the title duplication happens.

If you set per_page to 14 and you have 14 items, you get the "(Move up or down to reveal more choices)" even though there's only one page of items.

**Comment by piotrmurach** [comment]
Currently the `per_page` is per specific prompt configuration option. I don't see a problem why we couldn't have it as a `TTY::Prompt.new` configuration option. I will see if I've got time to fix it today.

**Comment by piotrmurach** [comment]
@keepcosmos Released `v0.11.0`. Enjoy!

**Comment by keepcosmos** [comment]
@piotrmurach Thanks 👍
