### ISSUE TITLE
Ruby 2.4: Title line of select gets repeated when using prompt.publish

### ISSUE THREAD

**Issue by muellerj** [piotrmurach/tty-prompt#35]
I just tried upgrading to Ruby 2.4 and found a weird bug concerning the behaviour of the `promt.select` menu when working with `prompt.publish`. Minimal working example:

``` ruby
require "tty-prompt"

prompt = TTY::Prompt.new

prompt.on(:keypress) do |event|
  if event.key.name == 'j'
    prompt.publish(:keydown)
  end

  if event.key.name == 'k'
    prompt.publish(:keyup)
  end
end

choice = prompt.select("Select drinks?", marker: ">") do |menu|
  menu.choice :vodka
  menu.choice :beer
  menu.choice :wine
  menu.choice :whisky
  menu.choice :bourbon
end

puts "Your choice: #{choice}"
```

Under Ruby 2.3, the behaviour is as expected:

``` shell
projects/tty-prompt-bug [2h|master] (1) ruby minimal-example.rb
Select drinks? wine
Your choice: wine
```

When switching to Ruby 2.4, the title line of the select prompt gets printed in a new line each time the selection is changed using `j` or `k`:

``` shell
projects/tty-prompt-bug [2h|master] (1) ruby minimal-example.rb
Select drinks? (Use arrow keys, press Enter to select)
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks? wine
Your choice: wine
```

When I use the arrow-keys instead, the title line gets no extra repititions.

The version of `tty-prompt` is `0.10.0` in both cases. I compared Ruby `2.3.1p112` with `2.4.0p0`.

**Comment by piotrmurach** [comment]
Thanks for reporting. Interesting behaviour, sometimes what happens with issues like that, there may be an error produced that is masked by prompt printing over it. At the moment I'm nearly finished with completely rewriting how keyboard input is handled to make this library work well on Windows. I don't want to attempt fixing too many issues in a single release. I will first release `v0.11.0` and see if that may potentially fix itself. Would it be possible for yourself to try the current master branch by pointing your Gemfile source to this repo?

**Comment by muellerj** [comment]
The problem persists on the current master: 

``` shell
projects/tty-prompt-bug [45m|master] (1) cat Gemfile
source "https://rubygems.org"

gem "tty-prompt", git: "https://github.com/piotrmurach/tty-prompt", branch: "master"

projects/tty-prompt-bug [43m|master] (1) bundle
Fetching https://github.com/piotrmurach/tty-prompt
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using equatable 0.5.0
Using necromancer 0.3.0
Using tty-color 0.4.0
Using wisper 1.6.1
Using bundler 1.13.7
Using pastel 0.7.1
Using tty-prompt 0.10.0 from https://github.com/piotrmurach/tty-prompt (at master@652a843)
Bundle complete! 1 Gemfile dependency, 7 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
projects/tty-prompt-bug [43m|master] (1) fg
[1]  + continued  vim Gemfile

zsh: suspended  vim Gemfile
projects/tty-prompt-bug [43m|master] (1) ruby minimal-example.rb
Select drinks? (Use arrow keys, press Enter to select)
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks?
Select drinks?
  vodka
  beer
> wine
  whisky
  bourbon
```

**Comment by piotrmurach** [comment]
That's a shame... Do you have time to poke around the codebase? All the code for this prompt is [here](https://github.com/piotrmurach/tty-prompt/blob/master/lib/tty/prompt/list.rb#L203), and I would probably comment out screen refreshing first to see if no errors are printed out between key presses and to see what different characters get printed. If you manage to fix the bug please submit PR. Cherry on the top would be if there is a test trapping the bug. The more help I can get the quicker things get done.

**Comment by muellerj** [comment]
I'm having trouble setting up my minimal example to use my local version of `tty-prompt`. Will try again tonight.

**Comment by piotrmurach** [comment]
To save you time you can use already present examples such as [select example](https://github.com/piotrmurach/tty-prompt/blob/master/examples/select.rb). When you checkout the repo I would suggest commenting out all the Gemfile dependencies as they are made to work for Ruby 1.9.3 but will fail to install on Ruby 2.4.0 and you don't need them to run tests or the library code. That should make it smoother. Any problems please don't hesitate to let me know. I have few tty libraries that I want to release asap.

**Comment by muellerj** [comment]
I don't think you should hold the release due to this issue, since the problem is present in 0.10.0 with ruby 2.4 as well. 

I'm sorry for not having more time at the moment.

**Comment by piotrmurach** [comment]
No worries, the other tty libraries that I'm referring to have nothing to do with this library release. I suppose tty-prompt will be released when its ready. If you have time to help that's fine, I do appreciate any help.

**Comment by muellerj** [comment]
It seems I'm having trouble getting the `publish` to work at all when working against the local gem version. Im both cases, I press `j` followed by `↓` followed by `return` when presented with the select-menu.

``` sh
projects/tty-prompt [4d|master*] cat examples/select.rb 
# encoding: utf-8

require 'tty-prompt'

prompt = TTY::Prompt.new

warriors = %w(Scorpion Kano Jax)

prompt.on(:keypress) do |event|
  if event.key.name == 'j'
    prompt.publish(:keydown)
  end
  if event.key.name == 'k'
    prompt.publish(:keyup)
  end
end

prompt.select('Choose your destiny?', warriors)
projects/tty-prompt [4d|master*] cat .ruby-version 
2.3
projects/tty-prompt [4d|master*] ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
projects/tty-prompt [4d|master*] bundle exec ruby examples/select.rb
Choose your destiny? Kano
projects/tty-prompt [4d|master*] echo "2.4" > .ruby-version 
projects/tty-prompt [4d|master*] ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
projects/tty-prompt [4d|master*] bundle exec ruby examples/select.rb
Choose your destiny? Kano
```

The behaviour is identical under both Rubies. Upon the `j`-keypress, nothing happens, the `↓`-keypress advances the selection 1 item down (as expected). This is different to the behaviour when I source `tty-prompt` as an external gem in another project, but I have no idea why.

**Comment by piotrmurach** [comment]
The `Reader` has been completely rewritten to make it work on Windows. And I think the key events naming has slightly changed. What you need to do is call `event.key.name == :alpha && event.value == 'j'` in order to publish event. The `:keyup` and `:keydown` are still the same.

**Comment by muellerj** [comment]
After updating to the latest commits, I can now reproduce the behaviour. In both instances, I press `j`, `j`, `return`.

``` sh
projects/tty-prompt [9h|master**] (1) echo "2.3" > .ruby-version
projects/tty-prompt [9h|master**] (1) ruby examples/select.rb
Choose your destiny? Jax
projects/tty-prompt [9h|master**] (1) echo "2.4" > .ruby-version
projects/tty-prompt [9h|master**] (1) ruby examples/select.rb
Choose your destiny? (Use arrow keys, press Enter to select)
‣ Scorpion
Choose your destiny?
  Scorpion
Choose your destiny? Jax
projects/tty-prompt [9h|master**] (1)
```

The run under Ruby 2.4 fails to clear the first two lines of the old menu. I will now try the force this into a spec.

**Comment by piotrmurach** [comment]
At the moment I'm struggling with making `ask` work correctly across different systems. It proves a bit harder than I thought. Anyhow, you never know this issue may turn out to be a bug in Ruby 2.4 :) Cheers for looking into this.

**Comment by muellerj** [comment]
Just for my reference: When I reproduce the same example on a system running OSX, only the first line (containing the question) doesn't get deleted. Again, with 2.3 the behaviour is o.k.. The Ruby versions here are `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]` and `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]` respectively.

**Comment by piotrmurach** [comment]
@muellerj Any luck fixing this issue? You may want to update from master as quite few things have changed which may have an impact.

**Comment by muellerj** [comment]
I haven't spent any significant time on it, but the problem still persists:

```ruby
projects/tty-prompt [34h|master*] (1) bundle exec ruby -e "require 'tty-prompt'; puts TTY::Prompt::VERSION"
0.10.1
projects/tty-prompt [34h|master*] (1) echo "2.3" > .ruby-version
projects/tty-prompt [34h|master*] (1) bundle exec ruby examples/select.rb
Choose your destiny? Jax
projects/tty-prompt [34h|master*] (1) echo "2.4" > .ruby-version
projects/tty-prompt [34h|master*] (1) bundle exec ruby examples/select.rb
Choose your destiny? (Use arrow keys, press Enter to select)
‣ Scorpion
Choose your destiny?
  Scorpion
Choose your destiny? Jax
```
*(In both cases, I press `j`, `j` followed by `⏎` at the prompt)*

**Comment by muellerj** [comment]
So here is a spec, which tries to reproduce the behaviour (lives in `spec/unit/select_spec.rb`):

```ruby
  it "allows navigation using events" do
    puts RUBY_VERSION
    choices = %w(Large Medium Small)
    prompt.input << "j" << "\r"
    prompt.input.rewind
    prompt.on(:keypress) do |event|
      prompt.publish(:keydown) if event.value == 'j'
    end
    expect(prompt.select('What size?', choices, marker: '>')).to eq("Medium")
    # Escape-codes:
    #   2K = clear line
    #   1G = Pos1
    #   1A = move up one line
    expect(prompt.output.string).to eq([
      "\e[?25lWhat size? \e[90m(Use arrow keys, press Enter to select)\e[0m\n",
      "\e[32m> Large\e[0m\n",
      "  Medium\n",
      "  Small",
      "\e[2K\e[1G\e[1A" * 3,
      "\e[2K\e[1G",
      "What size? \n",
      "  Large\n",
      "\e[32m> Medium\e[0m\n",
      "  Small",
      "\e[2K\e[1G\e[1A" * 3,
      "\e[2K\e[1G",
      "What size? \e[32mMedium\e[0m\n\e[?25h"
    ].join), "Received #{prompt.output.string.inspect}"
  end
```

When I run it under Ruby 2.3, it passes (as expected):

```sh
projects/tty-prompt [35h|master**] (1) echo "2.3" > .ruby-version
projects/tty-prompt [35h|master**] (1) bundle exec rspec spec/unit/select_spec.rb:25
Run options: include {:locations=>{"./spec/unit/select_spec.rb"=>[25]}}

Randomized with seed 31956

TTY::Prompt#select
2.3.1
  allows navigation using events

Top 1 slowest examples (0.007 seconds, 63.6% of total time):
  TTY::Prompt#select allows navigation using events
    0.007 seconds ./spec/unit/select_spec.rb:25

Finished in 0.011 seconds (files took 0.85309 seconds to load)
1 example, 0 failures

Randomized with seed 31956
```

When I run it under Ruby 2.4, it still passes (albeit with a warning about `Forwardable`):

```sh
projects/tty-prompt [35h|master**] (1) echo "2.4" > .ruby-version
projects/tty-prompt [35h|master**] (1) bundle exec rspec spec/unit/select_spec.rb:25
Run options: include {:locations=>{"./spec/unit/select_spec.rb"=>[25]}}

Randomized with seed 63624

TTY::Prompt#select
2.4.0
/cygdrive/c/Users/q284114/projects/tty-prompt/spec/unit/select_spec.rb:31:in `block (3 levels) in <top (required)>': TTY::Prompt#publish at /cygdrive/c/Users/q284114/.rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method TTY::Prompt::Reader#publish
  allows navigation using events

Top 1 slowest examples (0.005 seconds, 100.0% of total time):
  TTY::Prompt#select allows navigation using events
    0.005 seconds ./spec/unit/select_spec.rb:25

Finished in 0.005 seconds (files took 0.46205 seconds to load)
1 example, 0 failures

Randomized with seed 63624
```

I have no idea where the difference in behaviour could come from, given the same string is emitted both times. Does Ruby 2.4 do some sort of post-processing on the escape-codes before it forwards them to the terminal?

**Comment by muellerj** [comment]
Update: After a short Google-search, [this ruby issue](https://bugs.ruby-lang.org/issues/12782) might be the problem?

**Comment by muellerj** [comment]
Update #2: Unless the warning screws up the escape-code handling, I don't think it matters to the operation of the code. It also seems like on the current master of `whisper`, the method `Whisper::Publisher#publish` is not private anymore, so the warning should not occur anymore. I'll try updating `whisper` to `2.0` to see if that helps.

**Comment by muellerj** [comment]
Update #3: The warning from `Forwardable` is actually the problem - maybe it eats up some of the escape-codes? If I make `Wisper::Publisher#publish` public, the issue is resolved. 

Contrary to my previous comment, `2.0.0-rc1` of `wisper` still has `#publish` defined as private (see https://github.com/krisleech/wisper/blob/master/lib/wisper/publisher.rb#L50).

So I see several ways to resolve this:

* Raise an issue over at `wisper` to see why `#publish` is defined private
* Make the output stream robust against warnings
* Use a different mechanism to delegate `#publish`

Hope this helps.

**Comment by piotrmurach** [comment]
Thanks a ton for looking into this! Yeah, this makes total sense, if there are warnings emitted to standard output, the clearing behaviour doesn't account for that. As a consequence, it only clears the expected lines minus the warning, hence the selection starts to 'travel' down the terminal producing duplication of titles etc... I'm not sure there is a way around counting the warnings in.

I must say it sound rather strange for `Wisper::Publisher#publish` or `Wisper::Publisher#broadcast` to be private when it is the official way to fire events as documented in Readme - ( see https://github.com/krisleech/wisper/blob/master/lib/wisper/publisher.rb#L50). Any key event is fired through wisper pub/sub. This explains why when you use arrow keys things work fine. As the reader by including `Wisper::Publisher` has access to private publish call. However, when you define your custom key events like listening for `j` key then publish event is delegated to reader and hence we get error/warning. Would you mind opening a ticket at wisper and questioning this with the author? I would like to avoid implementing my own pub/sub.

The warnings could be silenced but I would rather avoid doing this as in future it will be next to impossible to fix cases like this one. Things will silently fail like events sub/pub and we won't have much to go on.

Again, thank you very much this is super useful! ❤️

**Comment by piotrmurach** [comment]
Cheers for creating the ticket. Do you have a minute to submit PR with your test case. This should fail travis build for `2.4.0` and give me some room to see if I can find some clean solution to this problem without breaking current apis.

**Comment by muellerj** [comment]
Sure. Can you give me a short heads-up, how I can create a full-stack test, that would not only make assertions about the `prompt.output.string` but exercises the whole system?

**Comment by piotrmurach** [comment]
The test is really useful as is. I believe it does exercise the whole stack really from creating the prompt to looking at the output. Potentially, the only thing I would consider adding is to capture the standard error which I believe gets the warning message when `select` is called (see [rspec output matchers](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/output-matcher) and asserting that it is blank. This hopefully would fail on `2.4.0`.

**Comment by piotrmurach** [comment]
Sometimes the simplest solutions are the best. I have wrapped the private `publish` call with new public `emit` call which will be exposed as a new way to fire events. This will ensure that in future if `wisper` gets updated it won't clash with `broadcast` & `publish` methods. How do you feel about this solution?

**Comment by muellerj** [comment]
Looks fine to me. Maybe also update `README.md` and `examples/select.rb` with the new syntax?

**Comment by piotrmurach** [comment]
Updated examples and docs. Though at this stage I have still little internal dialog what api would be better `emit` or `trigger`. I have used `trigger` for firing events in `finite_machine` lib. Do you have any opinions on this?

**Comment by muellerj** [comment]
Hmm, `trigger` sounds a little more natural to me for firing an event on first glance, but I suppose both are suitable. I don't have a strong opinion on this one. 

Feel free to close this issue once your internal dialogue is satisfied ;)
