### ISSUE TITLE
Multiline input issue

### ISSUE THREAD

**Issue by keepcosmos** [piotrmurach/tty-prompt#44]
Thanks for upgrading v0.11.0

But, even though I pass empty line in multiline session, it does not return anything and I can not finish multiline session.  Could you check? :)

**Comment by piotrmurach** [comment]
Hey! The `multiline` is completely broken at the moment. It was implemented poorly last time round and I have virtually started rewriting this functionality and `keypress` yesterday 😄  I'm planning to get it done soon.

**Comment by keepcosmos** [comment]
Ok, thanks :)

**Comment by kke** [comment]
Came here to request a multiline input, looks like there already is one but it isn't kosher :)

I would like something notepadish/`<textarea>`ish with cursor navigation between lines. (launching $EDITOR could be an option)

**Comment by piotrmurach** [comment]
@kke To give you a bit of explanation of where I'm going with this feature. The idea is for `multiline` and effectively `Reader#read_line` is to work similar to what you expect from `irb` prompt. Currently `ask` pretty much has behaviour similar to Ruby standard `gets`. So what does it mean? Simply put, when you enter some characters and make a mistake you will have to delete the whole input up until the offending character. In so called `cooked` mode, which `gets` operates, pressing left/right arrows will render the characters back to terminal as `^[[D^[[C`. This is less than ideal.

Based on `irb` and what users generally expect from well behaved `posix` prompt, I intend for the left/right arrows to actually move cursor and allow insertion of text. For the up/down arrows it is generally expected that you will be navigating through history buffer. I have already implemented the history buffer just need to hook it up with the `Reader`. To achieve `irb` prompt like behaviour, I'm going have to put console into `raw` mode and separate control symbols from actual input manually. There is fair amount of complexity involved. I'm planning to roll it out initially to `multiline` prompt and then to `#ask`, `#yes?`, `#mask` respectively.

If I were to make the input allow up arrow to go up in actual screen, that would be unexpected behaviour and also would involve some mode switching akin to vim visual/insert modes. I'm not planning to open this can of worms :)

If you fancy launching an editor you can always use [tty-editor](https://github.com/piotrmurach/tty-editor) which has been specifically made for this use case. It already provides you with ability to choose your favourite editor when editing content.

**Comment by piotrmurach** [comment]
The `multiline` prompt should now work as expected. I've added [example](https://github.com/piotrmurach/tty-prompt/blob/master/examples/multiline.rb) to play with. All is implemented in master. Does it work for you?

**Comment by keepcosmos** [comment]
Thanks!!!! 👍

**Comment by keepcosmos** [comment]
@piotrmurach Thanks for fixing :) Any plan release new version is solved this issue?

**Comment by piotrmurach** [comment]
@keepcosmos Released `v0.12.0` with the new `multiline` prompt. Enjoy!
