### ISSUE TITLE
Yes/No with default = false has wrong capitalisation

### ISSUE THREAD

**Issue by carlosefonseca** [piotrmurach/tty-prompt#47]
The [docs](https://github.com/piotrmurach/tty-prompt#25-yesno) have this example for yes?/no?:
```ruby
prompt.yes?("Are you a human?") do |q|
  q.default false
  q.positive 'Yup'
  q.negative 'Nope'
end
# =>
# Are you a human? (yup/Nope)
```

So, from this code I expected this output:
```ruby
prompt = TTY::Prompt.new
prompt.yes?("Are you a human?") do |q|
  q.default false
end
# =>
# Are you a human? (y/N)
```
But what I'm getting is:
```ruby
# Are you a human? (Y/n)
```

I think this is a bug but, since the `default` parameter is not explained in the yes?/no? docs, I might be misinterpreting it.

**Comment by piotrmurach** [comment]
Agree. I think your expectation is correct, setting default should capitalise the default option. Do you fancy submitting a PR ?
