### ISSUE TITLE
Add something like per_page: nil, to show all items

### ISSUE THREAD

**Issue by cyclotron3k** [piotrmurach/tty-prompt#52]
I think it would be useful to have a shortcut for disabling pagination and displaying all items in a list.

Potential options:
```ruby
per_page: nil  # implies no per_page value is set
per_page: :all # descriptive
per_page: 0    # first non-meaningful integer
per_page: -1   # alludes to the final element of an array
```

**Comment by piotrmurach** [comment]
I'm not sure about of the options you have suggested:

```ruby
per_page: nil  # problematc - I'm never sure if it signifies absence of value or value of nil
per_page: :all # descriptive but adds extra branch in code, and potential for bugs
per_page: 0    # this feels like C magic where 0 got translated to false
per_page: -1   # dangerous since per_page is passed to array to take a slice and 
                       # make actually produce weird solution
```
Potentially I would consider `per_page: false` to explicitly tell the code to stop paginating.

The `:per_page` option simply takes a slice out of the choices so you can list all solutions by providing
```ruby
per_page: choices.size # always match choices size
# or 
per_page: Float::INFINITY # absurdly large value
```

One thing I definitely would add is the ability to configure this option for the prompt globally on instantiation.

**Comment by cyclotron3k** [comment]
Thanks @piotrmurach,

I already use the first technique you suggest, `choices.size`, but I thought it would be useful to have a shortcut to display all.

The reson I mentioned it was because I was trying to do something like this:
```ruby
prompt.select(
    "Title",
    some_array.map { ... }.select { ... }.compact.sort.blah.blah.blah,
   per_page: ?
)
```
