### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by ioquatix** [piotrmurach/tty-prompt#55]
This isn't an issue but I can't see how else to contact you.

I've created a demo video of a tool `cloudflare-dns-update` which uses `tty-prompt`.

https://www.youtube.com/watch?v=lQK6bWuQllM&feature=youtu.be&hd=1

I thought you might enjoy seeing how I've used your gem.

**Comment by piotrmurach** [comment]
Thanks for using `tty-prompt` and creating a demo! ❤️  Plus your accent is awesome, I could listen for hours!

I really enjoy seeing how people use tty libs to create useful tooling. That was the goal from the beginning to make it easy to put scripts together that give good user experience.

I'm not that hard to find on the inter webs 😄  Just followed you on twitter if you need to ping me in the future.

**Comment by ioquatix** [comment]
Thanks!

I've always worried about my accent so it's nice to know that it's better than okay :)

I will make some more videos.
