### ISSUE TITLE
Expander: Select / Show hint by default

### ISSUE THREAD

**Issue by hellola** [piotrmurach/tty-prompt#60]
I want to be able to tell the `Expander` to show the hint for the default option from startup. It seems like this is not possible through the usual API. Would this feature be considered acceptable if a pull request was made?

**Comment by piotrmurach** [comment]
Hi Ewoudt,

Thanks for trying `tty-prompt` out! Could you please provide an example of what you imagine the implementation with hint would do and look like? Once we agree on the workings, I'm more than happy to receive a PR!

**Comment by hellola** [comment]
Hello @piotrmurach,
I thought it would be easier just to write the patch and we can discuss the PR and possible changes, 

The PR I have created is [here](https://github.com/piotrmurach/tty-prompt/pull/95), it's very simple but I'm not sure if I've followed the project convention properly. 

Looking forward to your feedback
