### ISSUE TITLE
Copy-pasting a long string to prompt.ask causes prompt to repeat

### ISSUE THREAD

**Issue by kke** [piotrmurach/tty-prompt#62]
If you copy-paste a long string into `prompt.ask`, you will get something like:

![image](https://user-images.githubusercontent.com/3893/30580686-19a13fb8-9d26-11e7-83c3-bf12593df446.png)

Ref: https://github.com/kontena/kontena/issues/2838

**Comment by piotrmurach** [comment]
Hi Kimmo,

The latest `v0.14.0` fixes pasting long input! Tested on Windows as well and works well.
