### ISSUE TITLE
No-echo #ask adds to history

### ISSUE THREAD

**Issue by mahlonsmith** [piotrmurach/tty-prompt#68]
It feels like #ask with the 'echo: false' flag should behave in the same fashion as the #mask method -- not add to history.

Because it does, on the next #ask, you can simply up-arrow to see what was previously hidden.

Reproduction steps:

```ruby
prompt = TTY::Prompt.new
prompt.ask( "Say something sensitive!", echo: false )
prompt.ask( "Okay, now say something public.  Or up arrow for some juicy secrets!" )
```

**Comment by piotrmurach** [comment]
Hi Mahlon,

Boom! Thanks for reporting this important security issue! As it so happens I've rewrote tons of logic in [tty-reader](https://github.com/piotrmurach/tty-reader) which powers input processing. I will fix this one soon and let you know when ready to test. I expect to release new version of `tty-prompt` soon!

**Comment by piotrmurach** [comment]
Fixed in master branch! (see https://github.com/piotrmurach/tty-reader/commit/34182562284b747d4739f5e30d022a3f35978376)

**Comment by mahlonsmith** [comment]
Hey Piotr!  Thanks for the fast fix on this.  I'm enjoying the tty* suite!
