### ISSUE TITLE
Support list string matching

### ISSUE THREAD

**Issue by saveriomiroddi** [piotrmurach/tty-prompt#70]
It would be very useful to support string matching in lists - on user alphanumeric keypress, the entries would update to show only the ones matching the pattern provided (essentially, what the GitHub web interface does when you click on a menu like "Labels" and type something).

(Originally posted, by mistake, on issue #1).

**Comment by piotrmurach** [comment]
Hey Saverio!

Thanks for using this gem!

I really like your idea! I would like you to implement it for all the menus if possible.

**Comment by piotrmurach** [comment]
Released as part of `v0.15.0`.
