### ISSUE TITLE
Allow exit without selection in List

### ISSUE THREAD

**Issue by saveriomiroddi** [piotrmurach/tty-prompt#72]
It would be helpful to allow the user to exit a List without choosing anything, as it's a valid use case.

Esc would be a conventional candidate, but I think it's currently blocked by https://github.com/piotrmurach/tty-reader/issues/6

**Comment by saveriomiroddi** [comment]
ps. I've accidentally assigned myself.

**Comment by piotrmurach** [comment]
I'm not entirely convinced by this use case. The idea of selection is to either make a choice or rely on default choice. What would exiting list in a CLI tool mean, how useful would it be and what returned value would it give? Could you please demonstrate a real world use case when this scenario is desirable?

**Comment by saveriomiroddi** [comment]
I do have a real world use case! This is a simplified description; the user is actually me :smile: 

In an application of mine, one can set a parameter:

```sh
geet issue create --assignee saverio
```

If the parameter is `-`, tty-prompt is opened:

```sh
geet issue create --assignee -
```

For convenience, default parameters can be stored [WIP] in the configuration file. The problem, in this case, is that storing `-` as default will always force the user to choose something, even when he doesn't want to.
With the option not to choose anything, the user can quickly exit (

Returning `nil` would signify that the user didn't choose anything.

**Comment by piotrmurach** [comment]
Hmmmm.... I'm still not convinced as this feels like a code boundary to me. The parsing of command line options and its logic bleeds into how `tty-prompt` needs to react. I would argue that the option parsing should decide when to call prompt and when to skip it with default value. It feels to me a bit like a limitation of the CLI at the moment. Am I missing something here?

**Comment by saveriomiroddi** [comment]
> I would argue that the option parsing should decide when to call prompt and when to skip it with default value

The program can't :smile: 

Suppose a user (me) sets the defaults label for a PR creation to `-`.

If I want to create a PR with labels, the menu will show, and I will select the label.
Likely, at some point, I want to create a PR without labels; the menu will show, but I will exit.

The program can't know which will be the case.

Having no option to exit works when one doesn't choose a default, because in this case, the user knowns what is the case, and he will set the option accordingly (`-` if he wants a menu, or any other string for matching other labels).

I understand though, if this is not the responsibility of `tty-prompt` :smile:

**Comment by piotrmurach** [comment]
I'm not convinced - sorry 😉  You're complicating your life, a flag `--no-labels|--labels` is all you need. Your future potential users may thank you for the more explicit option. In any case, my goal with `tty-prompt` was to make it flexible so people can easily customise the behaviour. For example, if you need vim/emacs keybindings etc... In your instance you can listen for key events:

```ruby
prompt.on :keywhatever do |event|
  prompt.cursor.clear_lines(number_of_choices)
  ....
end
```

**Comment by suscodev** [comment]
I'd like to add additional support for being able to have *some* way of exiting a select list. I've been trying to use this tool for navigating a file structure--which may simply be beyond the scope of the tool--and I need to be able to exit back to a prior screen, but once a menu is displayed there's no way to send an interrupt to it.

**Comment by piotrmurach** [comment]
@suscodev Please see [menu example](https://github.com/piotrmurach/tty-prompt/blob/master/examples/menu.rb) that may help you construct a file structure menu. Instead of trying to use `esc` interrupt, you could consider using dot entry or spell out `back` entry to get back to the previous menu. Hope this helps!

**Comment by nonsenseless** [comment]
@piotrmurach Whoops, I posted that comment under the work account...but thank you! That's actually very helpful and I feel sheepish about not figuring it out myself.i

**Comment by piotrmurach** [comment]
@nonsenseless No worries. Glad could help!
