### ISSUE TITLE
Center text?

### ISSUE THREAD

**Issue by Awatatah** [piotrmurach/tty-prompt#77]
Just asking if there is a way to center the text in the terminal

**Comment by piotrmurach** [comment]
Yes, you can use [tty-screen](https://github.com/piotrmurach/tty-screen) to get current width and height of the terminal window. Calculate the center point and then use [tty-cursor](https://github.com/piotrmurach/tty-cursor) to position the text on your screen. See [star wars logo example](https://github.com/piotrmurach/tty-font/blob/master/examples/star_wars_logo.rb) on how it works.

Alternatively, you can use [strings](https://github.com/piotrmurach/strings#21-align) to align multiline strings together with `tty-screen` gem to provide current width for the center alignment.
