### ISSUE TITLE
The markers for select and multi_select are broken

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-prompt#78]
Hi,

On my system, the markers for `select` and `multi_select` are broken:
![image](https://user-images.githubusercontent.com/2405099/36149936-6913b69e-10ca-11e8-97f0-28688a65647f.png)

My system:
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
```

I noticed I am able to override the marker with both `list` and `multi_list`, but I also noticed that the `radio` markers [are hardcoded][1].

Finally - I ran a test to see all the symbols in your Symbols module, to see what is broken in my system, this is the result, in case it helps.

![image](https://user-images.githubusercontent.com/2405099/36150473-83b6f266-10cc-11e8-972e-3011d5718be3.png)

Happy to provide any additional info, or test any fix candidate.

[1]: https://github.com/piotrmurach/tty-prompt/blob/master/lib/tty/prompt/multi_list.rb#L102

**Comment by piotrmurach** [comment]
To be fair I'm really surprised about the behaviour of your system. It feels like you're missing some serious unicode support :smile: There is no guarantee if we were to replace these with any other symbols they would work fine for everyone. I would be more inclined to create a `theme` option which allows to provide your own set of symbols that take precedence and allow to customise stuff in one place for all the prompts?

**Comment by DannyBen** [comment]
Yeah... I spent some time trying to find what is the unicode secret sauce that my systemj is missing, with no luck.

The ability to override the `symbols` array would be a great workaround.

**Comment by piotrmurach** [comment]
This is now fully configurable via [:symbols](https://github.com/piotrmurach/tty-prompt#31-symbols) option either at prompt initialization or individually per each input type.
