### ISSUE TITLE
List navigation breaks down for long wrapped items

### ISSUE THREAD

**Issue by muellerj** [piotrmurach/tty-prompt#79]
I'm not sure this can be easily resolved, but I'll try and explain the issue nonetheless. Also, please feel free to change the assignment between `tty-prompt` and `tty-cursor` if you wish.

## Steps to reproduce:
Navigate a list (e.g. `examples/select.rb`), which has at lease one item, that wraps around under the current terminal width. Either add a very long item or resize the terminal to be "thin" enough.

## Expected behaviour
Normal list navigation

## Actual behaviour
The wrapped line now occupies two terminal rows instead of just one; the `#clear_line` from `TTY::Cursor` only eats one of them, leaving an artifact when the selection is changed (and `#refresh` is called accordingly). For example:

``` ruby
require_relative "../lib/tty-prompt"
prompt = TTY::Prompt.new

warriors = [
  "lkasjdlk ajsdl akjsdlkasj dlkasjd lkasjd lkasjd lkasjd lkasjd lkas",
  "askdj alsdkja slkdj aslkdjasl djlasjkd",
  "askdj slkdj aslkdjasl djlasjkd",
  "askdj alsdkja slkdj djlasjkd"
]

prompt.select('Choose your destiny?', warriors)
```
produces the following output on a terminal with 58 columns:

```
$ ruby examples/select.rb
Choose your destiny? (Use arrow keys, press Enter to select)
Choose your destiny?
Choose your destiny?
Choose your destiny?
Choose your destiny?
  lkasjdlk ajsdl akjsdlkasj dlkasjd lkasjd lkasjd lkasjd l
kasjd lkas
  askdj alsdkja slkdj aslkdjasl djlasjkd
‣ askdj slkdj aslkdjasl djlasjkd
  askdj alsdkja slkdj djlasjkd
```

I'm not sure if `TTY::Cursor#clear_line` should be made aware of wrapped lines, of if the list should be in charge of tracking long lines and calling `#clear_line` twice for these. Any thoughts?

**Comment by piotrmurach** [comment]
Hey Jonas!

Thanks for this detailed report! I knew issue of long input wrapping terminal size will materialise one day, though I had no stamina to tackle it so far😄 

The `tty-cursor` is a 'dumb' library which sole purpose is to generate required ansi codes and not to care how many lines to clear. Therefore, I would be inclined to address the issue in `tty-prompt` instead!

There is many ways to approach this issue but one thing that is certain is the need to use [tty-screen](https://github.com/piotrmurach/tty-screen) to measure the current terminal width. Then it should be possible to estimate how many lines you need to clear in total given measurements of each select option including the actual question. In this particular instance it is clear that one extra lines should be cleared in other for the `select` prompt to stay in place and stop 'traveling' down. 

Clearly this will affect pretty much all the menu selection prompts 😓 I think I've solved this issue for the `ask`, `mask` and similar prompts relying on user input by implementing [clear_display in tty-reader](https://github.com/piotrmurach/tty-reader/blob/master/lib/tty/reader.rb#L271). When typing user is able to input strings wrapping terminal width and navigate lines without any issue.

**Comment by muellerj** [comment]
One nice side-effect of implementing this inside `TTY::Cursor#clear_line` would be that it "Just Works" ©️ in all other places. It would however mean that that method has to know the contents of its current line somehow and I don't see how this is easily archived.

I will look into it as soon as I find some time - if someone else wants to have a stab in the meantime, please feel free.

**Comment by piotrmurach** [comment]
I feel that we're conflating two concepts here, one of the `display/screen line` and the other `text line`. The `tty-cursor#clear_line` clears a display line, it may be text but it also may be some color display or anything else, we don't know and we don't care. For example, if the text spans 7 display lines by calling `TTY::Cursor#clear_line` we only remove a single display line. This behaviour feels consistent to me. This is how I think about it. Consequently, I think it's better to figure a way to make it work in `tty-prompt`, I think I would go down the route of using `tty-screen` and create function that given the menu string is able to asses how many display lines it will take and hence how many lines to clear. Also, there are differences in how a line is understood by Unix systems vs Windows.

**Comment by muellerj** [comment]
I have opened a pull request with a naiive fix for `List` and `EnumList`. Please have a look if that is in the spirit of your last comment.

I have not included any tests, since testing the private `#terminal_linecount` does not seem like a good idea and I'm not sure if we should enable `TTY::TestPrompt` to gain a global setting about its width.

**Comment by piotrmurach** [comment]
Thanks for submitting your PR! It made me realise I've already implemented screen lines counting using in the tty-reader lib that I've previously pointed to. I've also added few examples for testing the output of `select` and `multi_select`. I agree that exposing screen width and adding tests maybe problematic. Please review and let me know if this is any good.

**Comment by muellerj** [comment]
Looks awesome - the implementation of your `#count_screen_lines` is almost identical to what I came up with inside the block: :+1: :smile: 

```ruby
def question_lines_count(question_lines)
  question_lines.reduce(0) do |acc, line|
    acc + @prompt.count_screen_lines(line)
  end
end

def count_screen_lines(line_or_size, screen_width = TTY::Screen.width)
  line_size = if line_or_size.is_a?(Integer)
                line_or_size
              else
                Line.sanitize(line_or_size).size
              end
  # new character + we don't want to add new line on screen_width
  new_chars = self.class.windows? ? -1 : 1
  1 + [0, (line_size - new_chars) / screen_width].max
end
```

vs.

```ruby
def terminal_linecount(lines, termwidth = TTY::Screen.width)
  lines.inject(0) do |sum, line|
    linewidth = @pastel.strip(line).length
    linecount = 1 + (linewidth - 1) / termwidth
    linecount = [1, linecount].max
    sum + linecount
  end
end
```

I haven't quite figured out the -1 on Windows plattforms, but the usecase described earlier is definitely fixed. Please consider this issue solved - I'll close the PR.

**Comment by piotrmurach** [comment]
Great minds think alike 😄 I needed to reinstall few things to make git and ssl work in my windows vm. After few checks I can verify that this works fine on Windows as well. I will release new version shortly.
