### ISSUE TITLE
Multi select does not mimic regular select 'enter' keypress

### ISSUE THREAD

**Issue by jesseduffield** [piotrmurach/tty-prompt#80]
If I have no selected options in a multiselect and I hit enter on the first one, I would rather it selected that option and exited the prompt rather than exit the prompt without selecting anything.

Could there be a flag sent into the multi_select method enabling this behaviour?

**Comment by piotrmurach** [comment]
Hi Jesse,

Thanks for using the library!

The help text informs `(Use arrow keys, press Space to select and Enter to finish)`, which means that hitting enter will always exit regardless of how many options are selected. Why would this prompt enter be consistent with `select` prompt? This is a different prompt. The idea behind multiple choice is that you can answer 0 to many questions. 

If you wish to have at least 1 question selected when user exits on enter then you can specify `:default` option to be the first choice. Then when user doesn't choose anything and immediately presses enter you will get your behaviour.

If we were to add this flag, imagine scenario where someone has menu with 5 options and user selects option 2 & 4, and the cursor is on item 3 and they press enter to exit but thanks to your addition they have also selected 3. Wouldn't that be confusing? Different behaviour of enter for different things?

I really cannot see value in this addition. However, if you submit PR I'm happy to review and potentially merge given a strong case.
