### ISSUE TITLE
How to test CLI scripts using `tty-prompt`?

### ISSUE THREAD

**Issue by kematzy** [piotrmurach/tty-prompt#81]
I'm using `tty-prompt` in a CLI script where I'm asking for various input and choices to output/append files and directories.  i.e.  `generate api-resource Developer`.

How can I run tests (using MiniTest) on these script files with a variety of chosen options??

Currently running tests stops and waits on each prompt (question) without showing the question, which prevents providing the correct response, apart from being irritating and making hundreds of tests useless.

Any advice or hints would be greatly appreciated.

**Comment by piotrmurach** [comment]
Hi @kematzy,

> Currently running tests stops and waits on each prompt (question) without showing the question, 

That's exactly what happens on blocking IO. The prompt waits for input which it never receives so it never completes. In your test you need to ensure that there is something to consume.

> apart from being irritating and making hundreds of tests useless.

`tty-prompt` doesn't make any of your tests useless. Your tests would suffer from the same issue if you replace the prompt with `gets` call that waits for input that it never receives.

What I'm going to say is that this question has nothing to do with `tty-prompt`. It could easily start with "How to test CLI scripts using `gets`?" 

Your frustration boils down to not knowing how to test blocking IO. For example, how would you test the following?

```ruby
$stdin.gets
```

There are many ways to test this, you can look at many tests in this project to see how I'm doing this. However, the method you choose is very specific to your setup.
