### ISSUE TITLE
Cannot capture ESC key

### ISSUE THREAD

**Issue by cnorman-enphase** [piotrmurach/tty-prompt#84]
I have this after creating a new prompt object:
  prompt.on(:keyescape) { |key| puts "You pushed #{key}" }

But while inside a menu, it doesn't work. This come next, and seems to block ESC from being captured:

  category = prompt.select("Choose a category:", %w(meter devices tunnels all_sws))

I'd like to be able to hit ESC while in a multi-select menu to back out and exit, or offer a message perhaps. How can we do this?

**Comment by piotrmurach** [comment]
Hi,

Thanks for using the library and reporting this issue!

The answer, for now, is no, you can't register to listen for `esc` key. This library relies on `tty-reader` to process character input and all the special keys and `esc` key make it difficult to get this right. For more information please read [this thread](https://github.com/piotrmurach/tty-reader/issues/6)

This month I'm rather busy and I won't be able to work on this. Sorry!

**Comment by piotrmurach** [comment]
With all due respect Chris but I don't think you fully appreciate the issue. It is not about reading a single character, that's a trivial problem, it's more about differentiating between `esc` and special keys such as up arrow which are preceeded by also `esc` key and are 'a single character' made up of three separate characters. Does that make sense?

**Comment by cnorman-enphase** [comment]
Ahhh gotcha, thank you!  That explains why it locked up when I swapped methods... woopsie.
Thanks again.  A tough case to crack indeed.

Chris Norman
Sr. Engineer, Software Support - Enphase Energy

**Comment by piotrmurach** [comment]
The latest `tty-reader` fixes [this issue](https://github.com/piotrmurach/tty-reader/commit/9a9a213ddcfdf50c68827b5db5127384f44834a7) and recognises the `Esc` key correctly.

Please install `tty-prompt` version `v0.18.0` with the fix!

**Comment by cnorman-enphase** [comment]
Hooray, thank you! Seems a bit tricky to catch though... I issue a break in my prompt.on block, and then rescue LocalJumpError, otherwise the menu just redraws itself.  There must be a better way.

**Comment by piotrmurach** [comment]
When you want to break from a block, `return` and `break` are not very useful as they will just return the current scope but won't finish the code execution. Try this:

```ruby
prompt.on(:keyescape) do |event|
  exit(1) 
  # this will return a shell exit code which you can
  # choose to be whatever you CLI needs 
end
```
