### ISSUE TITLE
`Prompt#ask` echoes fast input, even with echo disabled

### ISSUE THREAD

**Issue by woodruffw** [piotrmurach/tty-prompt#85]
Hi there,

I was doing some testing on a project that uses `tty-prompt`, and I noticed that `echo: false` doesn't stop characters from showing up on the terminal if the user types rapidly. Not everything shows up, but enough to partially compromise the privacy of the input.

Here's a live demo:
[![asciicast](https://asciinema.org/a/179767.png)](https://asciinema.org/a/179767)

Thanks for all the hard work on `tty-prompt`! It's been a pleasure to use :smile:

**Comment by piotrmurach** [comment]
Great to hear that you're enjoying using `tty-prompt`!

I think you need to stop typing fast 😉 I won't have time to investigate this anytime soon and definitely not this month as I'm busy preparing other tty projects for a conference. However, if you have some spare time then I would encourage you to look into [tty-reader](https://github.com/piotrmurach/tty-reader) which I believe to be the source of the bug as it is responsible for processing input and displaying it back in the console. That would be great help!

**Comment by woodruffw** [comment]
Thanks for the response!

I'll take a look at tty-reader in a bit.

**Comment by rpbaltazar** [comment]
Hi @woodruffw!

Have you had a chance to look into it? I was curious and tried it in my machine and you must be typing hella fast because I can't reproduce it. 😅
I've tested both with TTY reader and TTY prompt and I can't make it happen in any of them.

Maybe OS related? Does it happen in any specific OS or is it unrelated?

**Comment by woodruffw** [comment]
> Have you had a chance to look into it? I was curious and tried it in my machine and you must be typing hella fast because I can't reproduce it. sweat_smile

Yeah, I can't reproduce it any more either. I guess it got fixed some time in the last 7 months!

FWIW, the original OS was Linux (Ubuntu 16.04) running `urxvt` for the terminal emulator.
