### ISSUE TITLE
No input for special characters in select menu filtering

### ISSUE THREAD

**Issue by hedselu** [piotrmurach/tty-prompt#87]
### Describe the problem
Hi. While trying to use filter from [here](https://github.com/piotrmurach/tty-prompt#2622-filter), there is no possibility of typing special characters like @, #, $ etc.

```ruby
require 'tty-prompt'
prompt = TTY::Prompt.new
prompt.select('Filter out email:', %w[test1@mail.com test2@mail.com], filter: true)
```

* OS version: macOS High Sierra 10.13.6
* Ruby version: ruby-2.4.2

Tested on zsh-5.3 / bash-3.2

**Comment by piotrmurach** [comment]
Released `v0.17.1` with a fix.
